# Google does not publish an official Firebase emulator image, so we just make one

FROM node:24-alpine
ARG FIREBASE_VERSION=15.19.1
RUN apk --no-cache add openjdk21-jre bash curl && \
  npm cache clean --force && \
  npm i -g firebase-tools@$FIREBASE_VERSION
WORKDIR /srv/firebase
RUN printf '{ "emulators": { "auth": { "host": "0.0.0.0", "port": 9099 } } }\n' > firebase.json
EXPOSE 9099
ENTRYPOINT ["firebase", "emulators:start", "--only", "auth", "--project", "tasklet-app"]
